// user authentication types
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";

export const GET_CUSTOMER_WALLET_REQUEST = "GET_CUSTOMER_WALLET_REQUEST";
export const GET_CUSTOMER_WALLET_SUCCESS = "GET_CUSTOMER_WALLET_SUCCESS";
export const GET_CUSTOMER_WALLET_FAIL = "GET_CUSTOMER_WALLET_FAIL";

export const TXN_FUND_WALLET_REQUEST = "TXN_FUND_WALLET_REQUEST";
export const TXN_FUND_WALLET_SUCCESS = "TXN_FUND_WALLET_SUCCESS";
export const TXN_FUND_WALLET_FAIL = "TXN_FUND_WALLET_FAIL";

export const TXN_VTU_REQUEST = "TNX_VTU_REQUEST";
export const TXN_VTU_SUCCESS = "TNX_VTU_SUCCESS";
export const TXN_VTU_FAIL = "TNX_VTU_FAIL";

export const GET_DATA_PLANS_REQUEST = "GET_DATA_PLANS_REQUEST";
export const GET_DATA_PLANS_SUCCESS = "GET_DATA_PLANS_SUCCESS";
export const GET_DATA_PLANS_FAIL = "GET_DATA_PLANS_FAIL";

export const TXN_TOPUP_DATA_REQUEST = "TXN_TOPUP_DATA_REQUEST";
export const TXN_TOPUP_DATA_SUCCESS = "TXN_TOPUP_DATA_SUCCESS";
export const TXN_TOPUP_DATA_FAIL = "TXN_TOPUP_DATA_FAIL";

export const GET_CUSTOMER_TRANSACTIONS_REQUEST =
  "GET_CUSTOMER_TRANSACTIONS_REQUEST";
export const GET_CUSTOMER_TRANSACTIONS_SUCCESS =
  "GET_CUSTOMER_TRANSACTIONS_SUCCESS";
export const GET_CUSTOMER_TRANSACTIONS_FAIL = "GET_CUSTOMER_TRANSACTIONS_FAIL";

export const BULK_SMS_REQUEST = "BULK_SMS_REQUEST";
export const BULK_SMS_SUCCESS = "BULK_SMS_SUCCESS";
export const BULK_SMS_FAIL = "BULK_SMS_FAIL";

export const UPLOAD_CARD_REQUEST = "UPLOAD_CARD_REQUEST";
export const UPLOAD_CARD_SUCCESS = "UPLOAD_CARD_SUCCESS";
export const UPLOAD_CARD_FAIL = "UPLOAD_CARD_FAIL";

export const GET_UPLOADED_PINS_REQUEST = "GET_UPLOADED_PINS_REQUEST";
export const GET_UPLOADED_PINS_SUCCESS = "GET_UPLOADED_PINS_SUCCESS";
export const GET_UPLOADED_PINS_FAIL = "GET_UPLOADED_PINS_FAIL";

export const GET_MTN_REQUEST = "GET_MTN_REQUEST";
export const GET_MTN_SUCCESS = "GET_MTN_SUCCESS";
export const GET_MTN_FAIL = "GET_MTN_FAIL";

export const GET_AIRTEL_REQUEST = "GET_AIRTEL_REQUEST";
export const GET_AIRTEL_SUCCESS = "GET_AIRTEL_SUCCESS";
export const GET_AIRTEL_FAIL = "GET_AIRTEL_FAIL";

export const GET_9MOBILE_REQUEST = "GET_9MOBILE_REQUEST";
export const GET_9MOBILE_SUCCESS = "GET_9MOBILE_SUCCESS";
export const GET_9MOBILE_FAIL = "GET_9MOBILE_FAIL";

export const GET_GLO_REQUEST = "GET_GLO_REQUEST";
export const GET_GLO_SUCCESS = "GET_GLO_SUCCESS";
export const GET_GLO_FAIL = "GET_GLO_FAIL";

export const DELETE_ALL_PIN_REQUEST = "DELETE_ALL_PIN_REQUEST";
export const DELETE_ALL_PIN_SUCCESS = "DELETE_ALL_PIN_SUCCESS";
export const DELETE_ALL_PIN_FAIL = "DELETE_ALL_PIN_FAIL";

export const GET_ALL_PIN_REQUEST = "GET_ALL_PIN_REQUEST";
export const GET_ALL_PIN_SUCCESS = "GET_ALL_PIN_SUCCESS";
export const GET_ALL_PIN_FAIL = "GET_ALL_PIN_FAIL";

export const GENERATE_VOUCHER_REQUEST = "GENERATE_VOUVHER_REQUEST";
export const GENERATE_VOUCHER_SUCCESS = "GENERATE_VOUVHER_SUCCESS";
export const GENERATE_VOUCHER_FAIL = "GENERATE_VOUVHER_FAIL";

export const PHONEBOOK_CREATE_REQUEST = "PHONEBOOK_CREATE_REQUEST";
export const PHONEBOOK_CREATE_SUCCESS = "PHONEBOOK_CREATE_SUCCESS";
export const PHONEBOOK_CREATE_FAIL = "PHONEBOOK_CREATE_FAIL";

export const PHONEBOOK_GET_REQUEST = "PHONEBOOK_GET_REQUEST";
export const PHONEBOOK_GET_SUCCESS = "PHONEBOOK_GET_SUCCESS";
export const PHONEBOOK_GET_FAIL = "PHONEBOOK_GET_FAIL";

export const PHONEBOOK_DELETE_REQUEST = "PHONEBOOK_DELETE_REQUEST";
export const PHONEBOOK_DELETE_SUCCESS = "PHONEBOOK_DELETE_SUCCESS";
export const PHONEBOOK_DELETE_FAIL = "PHONEBOOK_DELETE_FAIL";

export const PURCHASE_BULK_EPIN_REQUEST = "PURCHASE_BULK_EPIN_REQUEST";
export const PURCHASE_BULK_EPIN_SUCCESS = "PURCHASE_BULK_EPIN_SUCCESS";
export const PURCHASE_BULK_EPIN_FAIL = "PURCHASE_BULK_EPIN_FAIL";

export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";

export const NEWSLETTER_REQUEST = "NEWSLETTER_REQUEST";
export const NEWSLETTER_SUCCESS = "NEWSLETTER_SUCCESS";
export const NEWSLETTER_FAIL = "NEWSLETTER_FAIL";

// newest api implementations
export const VERIFY_GOTV_REQUEST = "VERIFY_GOTV_REQUEST";
export const VERIFY_GOTV_SUCCESS = "VERIFY_GOTV_SUCCESS";
export const VERIFY_GOTV_FAIL = "VERIFY_GOTV_FAIL";

export const GET_PLANS_GOTV_REQUEST = "GET_PLANS_GOTV_REQUEST";
export const GET_PLANS_GOTV_SUCCESS = "GET_PLANS_GOTV_SUCCESS";
export const GET_PLANS_GOTV_FAIL = "GET_PLANS_GOTV_FAIL";

export const SUBSCRIBE_GOTV_REQUEST = "SUBSCRIBE_GOTV_REQUEST";
export const SUBSCRIBE_GOTV_SUCCESS = "SUBSCRIBE_GOTV_SUCCESS";
export const SUBSCRIBE_GOTV_FAIL = "SUBSCRIBE_GOTV_FAIL";

export const VERIFY_DSTV_REQUEST = "VERIFY_DSTV_REQUEST";
export const VERIFY_DSTV_SUCCESS = "VERIFY_DSTV_SUCCESS";
export const VERIFY_DSTV_FAIL = "VERIFY_DSTV_FAIL";

export const GET_PLANS_DSTV_REQUEST = "GET_PLANS_DSTV_REQUEST";
export const GET_PLANS_DSTV_SUCCESS = "GET_PLANS_DSTV_SUCCESS";
export const GET_PLANS_DSTV_FAIL = "GET_PLANS_DSTV_FAIL";

export const SUBSCRIBE_DSTV_REQUEST = "SUBSCRIBE_DSTV_REQUEST";
export const SUBSCRIBE_DSTV_SUCCESS = "SUBSCRIBE_DSTV_SUCCESS";
export const SUBSCRIBE_DSTV_FAIL = "SUBSCRIBE_DSTV_FAIL";

// vtpass Topup
export const VT_AIRTIME_REQUEST = "VT_AIRTIME_REQUEST";
export const VT_AIRTIME_SUCCESS = "VT_AIRTIME_SUCCESS";
export const VT_AIRTIME_FAIL = "VT_AIRTIME_FAIL";

export const VT_DATA_REQUEST = "VT_DATA_REQUEST";
export const VT_DATA_SUCCESS = "VT_DATA_SUCCESS";
export const VT_DATA_FAIL = "VT_DATA_FAIL";

export const VT_QUERY_DATA_REQUEST = "VT_QUERY_DATA_REQUEST";
export const VT_QUERY_DATA_SUCCESS = "VT_QUERY_DATA_SUCCESS";
export const VT_QUERY_DATA_FAIL = "VT_QUERY_DATA_FAIL";

// smile internet subscription
export const QUERY_SMILE_REQUEST = "QUERY_SMILE_REQUEST";
export const QUERY_SMILE_SUCCESS = "QUERY_SMILE_SUCCESS";
export const QUERY_SMILE_FAIL = "QUERY_SMILE_FAIL";

export const VERIFY_SMILE_REQUEST = "VERIFY_SMILE_REQUEST";
export const VERIFY_SMILE_SUCCESS = "VERIFY_SMILE_SUCCESS";
export const VERIFY_SMILE_FAIL = "VERIFY_SMILE_FAIL";

export const SMILE_DATA_REQUEST = "SMILE_DATA_REQUEST";
export const SMILE_DATA_SUCCESS = "SMILE_DATA_SUCCESS";
export const SMILE_DATA_FAIL = "SMILE_DATA_FAIL";

// spectranet Internet subscription
export const QUERY_SPECTRANET_REQUEST = "QUERY_SPECTRANET_REQUEST";
export const QUERY_SPECTRANET_SUCCESS = "QUERY_SPECTRANET_SUCCESS";
export const QUERY_SPECTRANET_FAIL = "QUERY_SPECTRANET_FAIL";

export const SPECTRANET_DATA_REQUEST = "SPECTRANET_DATA_REQUEST";
export const SPECTRANET_DATA_SUCCESS = "SPECTRANET_DATA_SUCCESS";
export const SPECTRANET_DATA_FAIL = "SPECTRANET_DATA_FAIL";

// edit customer profile
export const EDIT_CUSTOMER_REQUEST = "EDIT_CUSTOMER_REQUEST";
export const EDIT_CUSTOMER_SUCCESS = "EDIT_CUSTOMER_SUCCESS";
export const EDIT_CUSTOMER_FAIL = "EDIT_CUSTOMER_FAIL";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

